//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qrator.ServerData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeTest
    {
        public PracticeTest()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Source { get; set; }
        public int ExaminationID { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string MasterCode { get; set; }
        public short Status { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
    }
}
